# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0003_auto_20150527_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageWithComments',
            fields=[
                ('richtextpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.RichTextPage')),
                ('comments_count', models.IntegerField(default=0, editable=False)),
            ],
            options={
                'ordering': ('_order',),
            },
            bases=('pages.richtextpage',),
        ),
    ]
